__include__: [
  '../dataset/gr_detection.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd.yml',
  '../runtime.yml',
]

# Using split-test from fisrt experiment 

num_classes: 5 # Has to be actual number of classes + 1
epoches: 160

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /home/ros/visionai_platform/data
    ann_file: /home/ros/visionai_platform/data/datasets/image-ir/experiments/e25-004-d25-004-ir-sc16862/coco_labels/split_train.mapped.json
    return_masks: False
    transforms:
      type: Compose
      ops:
        - {type: RandomZoomOut, fill: 0}
        - {type: RandomIoUCrop, p: 0.9}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: RandomHorizontalFlip}
        - {type: Resize, size: [640, 640], }
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}   
        - {type: ConvertBoxes, fmt: 'cxcywh', normalize: True}
        - {type: RandomPhotometricDistort, p: 0.5}


      policy:
        epoch: 117
  collate_fn:
    type: BatchImageCollateFuncion  
    scales: ~
  total_batch_size: 16
  shuffle: True
  num_workers: 8
  drop_last: True 

val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /home/ros/visionai_platform/data
    ann_file: /home/ros/visionai_platform/data/datasets/image-ir/experiments/e25-004-d25-004-ir-sc16862/coco_labels/split_test.mapped.json
    return_masks: False
    transforms:
      type: Compose
      ops: 
        - {type: Resize, size: [640, 640]}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}   
  total_batch_size: 16
  shuffle: False
  num_workers: 8
  drop_last: False
  collate_fn:
    type: BatchImageCollateFuncion  

PResNet:
  depth: 34
  freeze_at: -1
  freeze_norm: False
  pretrained: True


HybridEncoder:
  in_channels: [128, 256, 512]
  hidden_dim: 256
  expansion: 0.5

RTDETRTransformerv2:
  num_layers: 3


optimizer:
  type: AdamW
  params:
    - 
      params: '^(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

eval_spatial_size: [640, 640]
fix_dimensions: True