__include__: [
  '../dataset/gr_detection.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd.yml',
  '../runtime.yml',
]


num_classes: 5 # Has to be actual number of classes + 1
epoches: 1

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /home/ros/visionai_platform/data
    # ann_file: /home/ros/visionai_platform/data/datasets/image-ir/experiments/e25-001-d25-001-ir-sc15319-poc/coco_labels/split_train.mapped.json
    ann_file: /home/ros/visionai_platform/data/datasets/image-ir/experiments/e25-002-d25-002-ir-sc16862/coco_labels/split_train.mapped.json
    
    return_masks: False
    transforms:
      type: Compose
      ops:
        - {type: RandomZoomOut, fill: 0}
        - {type: RandomIoUCrop, p: 0.8}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: RandomHorizontalFlip}
        - {type: Resize, size: [640, 640], }
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}   
        - {type: ConvertBoxes, fmt: 'cxcywh', normalize: True}    

      policy:
        epoch: 150
  collate_fn:
    type: BatchImageCollateFuncion  
    scales: ~
  # total_batch_size: 18
  total_batch_size: 16
  shuffle: True
  num_workers: 8
  drop_last: True 

val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /home/ros/visionai_platform/data
    # ann_file:  /home/ros/visionai_platform/data/datasets/image-ir/experiments/e25-001-d25-001-ir-sc15319-poc/coco_labels/split_test.mapped.json
    ann_file:    /home/ros/visionai_platform/data/datasets/image-ir/experiments/e25-002-d25-002-ir-sc16862/coco_labels/split_test.mapped.json

    return_masks: False
    transforms:
      type: Compose
      ops: 
        - {type: Resize, size: [640, 640]}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}   
  total_batch_size: 16
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFuncion  

PResNet:
  depth: 34
  freeze_at: -1
  freeze_norm: False
  pretrained: True
  
HybridEncoder:
  in_channels: [128, 256, 512]
  hidden_dim: 256
  expansion: 0.5



RTDETRTransformerv2:
  num_layers: 3

  num_denoising: 80
  label_noise_ratio: 0.6
  box_noise_scale: 0.9 # 1.0 0.4



optimizer:
  type: AdamW
  params:
    - 
      params: '^(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

eval_spatial_size: [640, 640]
fix_dimensions: True